services:
  ex-dock:
    build: .
    volumes:
      - ./config:/app/config
    ports:
      - "8888:8888"
    networks:
      - ex-dock
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ex-dock
    volumes:
      - ./database/ex-dock.sql:/docker-entrypoint-initdb.d/datadump.sql
      - ./application-files:/app/application-files
    ports:
      - "8890:5432"
    networks:
      - ex-dock

networks:
  ex-dock:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
